# Generated by Django 2.0.7 on 2018-07-23 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True)),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
