# Generated by Django 2.0.7 on 2018-07-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
